### ISSUE TITLE
[Bug] App crashes on few specific pages when "Crop Borders" is enabled

### ISSUE THREAD

**Issue by moka491** [tachiyomiorg/tachiyomi#4357]
## Device information
* Tachiyomi version: v3045 (also tested with stable 0.10.7, where this does *not* occur)
* Android version: 11
* Device: Pixel 3a

## Steps to reproduce
0. Use the newest preview build v3045
1. Install the Mangadex extension and login
2. Search "Sewayaki Kitsune no Senko-san" and add it to your library
3. Enable "Crop Borders" in the reader settings. Turning this on will reproduce the bug, turning it off will "fix" it.
4. Open either Chapter 25 and scroll to page 17, or Chapter 39 and scroll to page 3.

### Expected behavior
The page should be shown correctly, even with "Crop borders" enabled. 

### Actual behavior
The app crashes upon visiting either of the two pages. 
Again, this does not happen when "Crop borders" is disabled.

## Other details
1. This bug was initially found and analyzed in the Neko fork, and then reproduced in Tachiyomi r3045. See the issue here for the initial findings: https://github.com/CarlosEsco/Neko/issues/406

2. This bug was reproduced with Mangadex, since the Neko fork is limited to Mangadex as well. I have quickly tested it against 2 other sources, Mangasee and Mangapark but they seem to use different image files in general (from a different scanlation group), hence I couldn't reproduce it.

**Comment by taichikuji** [comment]
Tried to reproduce it. No problems on my end. Having a Xiaomi Redmi Note 7 with Android 10 and using Tachiyomi dev version r3045 and MangaDex plugin with version 1.2.103.

**Comment by arkon** [comment]
I also couldn't reproduce, but it's likely an issue with the new image decoder.

Can you post the crash logs too? (More > Settings > Advanced > Dump crash logs)

**Comment by moka491** [comment]
Yeah, here's the logs [tachiyomi_crash_logs.txt](https://github.com/tachiyomiorg/tachiyomi/files/5876547/tachiyomi_crash_logs.txt)

It was a freshly installed r3045 I tested it with, so it's on default settings with nothing changed but the Crop Borders setting.
It might also be Android 11 specific, I don't know.

**Comment by inorichi** [comment]
Please try this again once there's a new preview version available. I couldn't reproduce this issue but maybe it was fixed with the latest changes.

**Comment by moka491** [comment]
I will, thank you for your hard work. Just tested it again with r3128 and it still happens. Once there's a new build, I'll make sure to give it a try once more.
I get the feeling that this is some edge case that only happens on my device, perhaps OS specific, perhaps dependent on the screen resolution or ratio, no clue. If the new update fixes it, we'll see :)

**Comment by moka491** [comment]
@inorichi r3130 fixes it, I can't reproduce the problem anymore, where with the previous version I could.

Thank you so much for taking the time to work this out!
