### ISSUE TITLE
Batch delete of downloaded chapters.

### ISSUE THREAD

**Issue by sarweshmaharjan** [tachiyomiorg/tachiyomi#4924]
## Device information
* Tachiyomi version: 0.10.11
* Android version: 8
* Device: Samsung S7

## Steps to reproduce
1. Download lots of chapter for any manga (10 or more). 
2. Do this for bunch of manga. 
3. Either deleting them by selecting multiple manga and doing "delete" action. 
4. It doesn't delete the downloaded chapters. You have to manually do it 1 chapter by 1 chapter. 

### Expected behavior
When I batch delete, it should have deleted all the downloaded chapter and refresh the badges count back to zero. 

### Actual behavior
Instead, it doesn't change at all. When i refresh my app, it still shows there is downloaded chapter in it. 

## Fixes
A indicator of some sort like how downloaded chapter can be viewed from setting, something like that should be better to let user know if the downloaded chapter are being deleted or not.

**Comment by paulo27ms** [comment]
Can you consistently reproduce this? It's "normal" for the badge to not update right after deleting but closing and reopening the app should fix it.
I have been clearing a lot of manga recently and haven't noticed issues with deletions.

**Comment by sarweshMaharjan** [comment]
Yes i have been getting this issue alot. I tried to close and re-open it, still didn't got fixed. I tried to do update, still not fixed.  I had to go and do it 1 chapter at a time and it finally deleted itself.

**Comment by arkon** [comment]
Lumping this with #4286 for general slow deletion issue.
