### ISSUE TITLE
Using other trackers with the Komga tracker provides unexpected behavior

### ISSUE THREAD

**Issue by kiriya-aoi** [tachiyomiorg/tachiyomi#5699]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.0](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.12.0)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.12.1

### Android version

Android 11

### Device

Oneplus 7 Pro

### Steps to reproduce

1. Use Komga and add a series to your Komga library. In our example, let's say this series has 12 books.
2. Since this manga is probably released as volumes, set the sort number for each volume to the last chapter in that volume. Volume 1 happens to end at chapter 4 for our purposes, so it gets 4. Other volumes have some number greater than that.
    * This is so that in Tachiyomi reading progress can be synced to common manga trackers accurately, instead of using the volume number as the chapter number.
    * Alternately, you could simply be missing chapters 1-3 for some reason. You still don't want tracking to be wrong, so you set the sort number to the correct number for every other chapter and hope you'll add chapter 1-3 to Komga later.
3. Use the Komga source in Tachiyomi and enable tracking with Komga and at least one other tracker. Also set trackers to automatically update when you read a chapter.
4. Add the series from step 1. to your Tachiyomi library and track it with your other tracker (the Komga one should be added automatically).
5. Read the first chapter/book in the list in this series. This is either Volume 1 or Chapter 4, depending on which of the two examples we're following.

### Expected behavior

Komga tracker increments from 0 to 1, as I have read the first chapter/book from that series. This is the same behavior as you get when you have a series tracked only with the Komga tracker.

Non-Komga tracker updates to 4, since that is the sort number it gets from Komga.

### Actual behavior

Non-Komga tracker behaves as expected and updates to chapter 4.

Komga tracker also updates to 4 (or lower, if the series happened to have fewer total books).
Opening the tracker sheet to see this triggers the reverse Komga-tracking, which then marks the first four books in Tachiyomi as read (despite, obviously, only ever having read the first one).

### Other details

This requires the "sort number" in Komga (which Tachiyomi uses to update tracking) to be higher than the ordinal position of that particular chapter/book. This may be the case with the use of volumes assigned a chapter number for tracking purposes, as is my use-case, or in the case of missing chapters.

I assume that when using only the Komga tracker the app is set to update it based on the ordinal position of the book, but when using other trackers it just pushes the sort number to every tracker (despite the Komga tracker requiring special handling).

**Comment by gotson** [comment]
I checked a bit the code, the sync 2 ways uses the index of chapters (https://github.com/tachiyomiorg/tachiyomi/blob/a69a8337169798710f9e0cd7072b3fd3be4a5917/app/src/main/java/eu/kanade/tachiyomi/util/chapter/ChapterTrackSync.kt), and Komga also uses the index on the backend.

Both should probably be updated to use the sort number, which is indeed set as the chapter number in the Komga extension.

To do that in a mon breaking way I could make a v2 of the api on Komga, and then we can update the code in Tachiyomi to use that v2 along with the fix in the above mentioned file.

**Comment by gotson** [comment]
After checking again the Track class, the last read is chapter is an Int, and the number sort is a decimal. I was curious as to why #5658 was converting chapter number to int, but now it makes more sense.

Given that limitation, switching to using the chapter number could have an impact on Komga tracking, where chapters with decimal numbers can't be marked as read properly I guess.

**Comment by gotson** [comment]
The latest preview R3799 should fix this. Can you check and confirm?

**Comment by kiriya-aoi** [comment]
The sync behavior is now as expected, the only other concern is the display of the tracker. It still shows the "maximum progress" as the total number of books in the series, rather than the highest sort number for the series.
![Screenshot_20210912-170522_Tachiyomi_1](https://user-images.githubusercontent.com/34067059/133002785-3f71085e-eccb-433b-b9b4-a8af7190d93c.png)

**Comment by gotson** [comment]
> The sync behavior is now as expected, the only other concern is the display of the tracker. It still shows the "maximum progress" as the total number of books in the series, rather than the highest sort number for the series.
> ![Screenshot_20210912-170522_Tachiyomi_1](https://user-images.githubusercontent.com/34067059/133002785-3f71085e-eccb-433b-b9b4-a8af7190d93c.png)

Thanks for the feedback. I knew the dialog wouldn't show exactly what's needed as the component expects a list of `Int`, but I didn't expect that 😂

Can you tell me what are the different `numberSort` for those 4 books in that series?

I will need to experiment, see what can be done.

Apart from the display, and the fact that you can't set it by number, are there any other undesired effects?

**Comment by kiriya-aoi** [comment]
The sort numbers are 5,12,19,30 for that series in particular.

Aside from that, the only thing about the two-way sync that doesn't work the way I'd expect is that there's only one way to mark something as unread. You have to mark a book as unread in both Tachiyomi and Komga, otherwise opening the tracker sheet to force sync will re-mark it as read. I don't really think of that as un-expected behavior, since Tachiyomi doesn't update trackers with a lower number.

**Comment by gotson** [comment]
> The sort numbers are 5,12,19,30 for that series in particular.

Thanks. In that case, what would you expect the field to show when clicked ?
- the list of `5,12,19,30` ?
- a list from `0` to `30` ?

> Aside from that, the only thing about the two-way sync that doesn't work the way I'd expect is that there's only one way to mark something as unread. You have to mark a book as unread in both Tachiyomi and Komga, otherwise opening the tracker sheet to force sync will re-mark it as read. I don't really think of that as un-expected behavior, since Tachiyomi doesn't update trackers with a lower number.

It is actually an implementation on Komga side:
- Komga will never mark anything unread when coming from Tachiyomi tracking
- Tachiyomi can send a lower tracking number AFAIK (i don't use other trackers so i don't know exactly how they behave)

The way it's currently done, it would be difficult to handle those changes that could come from both ways, because Tachiyomi doesn't keep a complete list of what chapters have been read and when, only what was the last chapter read. So we can't find the most recent update.

This brings more limitation, like when reading out of order. For example if you have 10 chapters, you have read 1-3, and you read 6, Tachiyomi will consider the last read as 6, but that would effectively mark 4-5 as read too. I understand the existing trackers don't have the same granularity that Komga, hence the design choice, but that also limits our options, unless we revamp that whole part in Tachiyomi.

I suppose the same problem would arise with #5658 once 2-way sync is enabled for all trackers.

**Comment by kiriya-aoi** [comment]
> > The sort numbers are 5,12,19,30 for that series in particular.
> 
> Thanks. In that case, what would you expect the field to show when clicked ?
> 
> * the list of `5,12,19,30` ?
> * a list from `0` to `30` ?

The first is preferable to me as those are the only significant options.

The second would give a way to manually track sub-progress (I read the first three parts of the first book, so I could set it to 3 as a reminder) but I don't think that would be a good option unless you also exposed that number in Komga. I'd rather omit it entirely, since we can't sync the page progress in a book.

I'm also not sure how this would handle a series with an interesting case of sort numbers, the first six are `12,25,38,51,51.13,64` with a whole book that does not contribute to the chapter numbering. That will be a big problem on the front of two-way for the other trackers Tachiyomi supports.

> > Aside from that, the only thing about the two-way sync that doesn't work the way I'd expect is that there's only one way to mark something as unread. You have to mark a book as unread in both Tachiyomi and Komga, otherwise opening the tracker sheet to force sync will re-mark it as read. I don't really think of that as un-expected behavior, since Tachiyomi doesn't update trackers with a lower number.
> 
> It is actually an implementation on Komga side:
> 
> * Komga will never mark anything unread when coming from Tachiyomi tracking
> * Tachiyomi can send a lower tracking number AFAIK (i don't use other trackers so i don't know exactly how they behave)
> 
> The way it's currently done, it would be difficult to handle those changes that could come from both ways, because Tachiyomi doesn't keep a complete list of what chapters have been read and when, only what was the last chapter read. So we can't find the most recent update.

AFAIK Tachiyomi does keep the what and the when for all chapters read, in the History pane if you delete the most recent read book for a series it will show the previous read book, and update to the date/time you read it. Whether that is actually accessible as a list I haven't checked.
If there's a way to implement it so that marking as unread went in at least one direction, that would be handy. At the very least I feel the current behavior is confusing.

> This brings more limitation, like when reading out of order. For example if you have 10 chapters, you have read 1-3, and you read 6, Tachiyomi will consider the last read as 6, but that would effectively mark 4-5 as read too. I understand the existing trackers don't have the same granularity that Komga, hence the design choice, but that also limits our options, unless we revamp that whole part in Tachiyomi.
> 
> I suppose the same problem would arise with #5658 once 2-way sync is enabled for all trackers.

It would definitely be ideal to allow for jumping around, but it seems like an expensive change to make.

**Comment by gotson** [comment]
> with a whole book that does not contribute to the chapter numbering

What does that mean? 

> AFAIK Tachiyomi does keep the what and the when for all chapters read, in the History pane if you delete the most recent read book for a series it will show the previous read book, and update to the date/time you read it. Whether that is actually accessible as a list I haven't checked.

It's not in the track object, it might be saved somewhere else.

**Comment by kiriya-aoi** [comment]
> > with a whole book that does not contribute to the chapter numbering
> 
> What does that mean?

Since I'm numbering books by the chapters they contain, and the series released an entire volume of prequel sidestories that don't get real chapter numbers, it's kind of annoying to deal with.

**Comment by gotson** [comment]
I did a bit of digging in the code base, here is what i found:
- `Track` only has `total_chapters`
- Komga currently set `Track.total_chapters` to the total number of books. This is incorrect for Series, and should instead be set to the max numberSort for Series only. That would require a non breaking change on the Komga API to add the field, and an update in Tachiyomi for the Komga Tracker.
- When clicking the number of chapters in Tachiyomi, a `MinMaxNumberPicker` is used to display the `0-max` list. We could imagine rolling another Picker that would be fed a list, but we still don't have the capability to store all the different chapter numbers inside the `Track` item.

**Comment by gotson** [comment]
I added the `maxNumberSort` in Komga locally, and changed the Komga Tracker in Tachiyomi. This is the result i get:

<img width="322" alt="Screenshot 2021-09-15 at 16 06 50" src="https://user-images.githubusercontent.com/2139133/133395440-d93d74be-895c-4a79-85db-747efa4190db.png">

I'm using the same numbers as your series (`5, 12, 19, 30`).

<img width="318" alt="Screenshot 2021-09-15 at 16 09 43" src="https://user-images.githubusercontent.com/2139133/133395584-57d65e58-59c8-410b-b6fe-ecf717abaa2b.png">

I think that's already good, and doesn't require much rework in Tachiyomi. In terms of behaviour, if you set a number that is not a chapter number, it will be rounded down to the previous chapter by the 2-way sync. So for example marking the chapter `15` as read would only mark as read the first 2 books.

**Comment by kiriya-aoi** [comment]
Yeah, that looks like a pretty good resolution.

**Comment by gotson** [comment]
Another solution would be:
- for the `Track` item to list explicitly all chapters, instead of just having the total number. It could be optional, and we could derive the list from the number (what is done currently in the `MinMaxNumberPicker`. We would need to update the database schema to cater for this.
- for the Tracker services to return the list of all chapters if they can. It would only be useful for Komga i think, i don't see the other trackers having an interest in doing so (apart maybe if a tracker is added for other selfhosting solutions like Kavita/Lanraragi/Mango).
- swap the `MinMaxNumberPicker` for a new picker that is fed a list.

It's quite some work, and probably only valuable for Komga. I'm not sure that would be accepted.

---

I'll release the change for Komga and submit a PR for Tachiyomi for the solution i proposed above.

**Comment by kiriya-aoi** [comment]
With https://github.com/tachiyomiorg/tachiyomi/pull/5917 merged and in preview for testing, it's safe to say the original issue has now been resolved.
