### ISSUE TITLE
Webp images get downloaded as .bin file

### ISSUE THREAD

**Issue by jopejoe1** [tachiyomiorg/tachiyomi#6156]
### Steps to reproduce

1. Download a chapter that has webp as image format (Important download chapter before trying to read it)
2. Read the chapter.

### Expected behavior

Chapter should open

### Actual behavior

Chapter does not load and error message no pages pops up

### Tachiyomi version

r3915

### Android version

10

### Device

Samsung Galaxy S10+

### Other details

If you open the chapter before downloading the download works perfectly fine.
Previously opened at jobobby04/TachiyomiSY#437

Some of the images that i have issues with can be found by:
1. Using Luscious Extension
2. set the image resolution to original in Luscious extension setting screen (other wise you download jpeg and not webp)
3. search and open `IRL Babes Vol. 1`
4. download any chapter ending with ` D`
5. open it after the download finishes 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by FourTOne5** [comment]
Seem like the bug has been fixed can you cross check since I'm using Bilibili Comics with webp as image format? I'm using r4011 btw.

**Comment by jopejoe1** [comment]
Just did some more testing and yeah bilibili comic with webp seems to be working totaly fine but webp from Luscious still not working no idear why one is working and the other one is not.

**Comment by alessandrojean** [comment]
My bet is because this extension probably doesn't set the `Content-Type` header in the response to `image/webp`. The responses must be analyzed and of it's the case probably the header needs to be added manually through an interceptor.

**Comment by jopejoe1** [comment]
> My bet is because their server probably doesn't set the `Content-Type` header in the response to `image/webp`. The responses must be analyzed and if it's the case probably the header needs to be added manually through an interceptor.

Yep that the issue here. Would have never thought of that.
