### ISSUE TITLE
Tachiyomi is not booted correct when network is not connected

### ISSUE THREAD

**Issue by brithbutter** [tachiyomiorg/tachiyomi#7203]
### Steps to reproduce

1. Turn off all internet connections including 4g and wifi.
2. Try to boot the Tachiyomi

### Expected behavior

Tachiyomi booted and I can read manga smoothly. 

### Actual behavior

Tachiyomi quits automatically.

### Tachiyomi version

0.13.4

### Android version

Android 12

### Device

Xiaomi 12 pro

### Other details

In the beginning, I noticed that the Tachiyomi quit automatically when I was reading manga. Soon after several tries, I noticed that this automatic quit is triggered by network conditions.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by brithbutter** [comment]
Further comments: I just noticed

**Comment by brithbutter** [comment]
Just in case the developer can not find this issue I reopen this issue.
Sincerely,

**Comment by arkon** [comment]
Please reopen this if you have crash logs to share.

**Comment by brithbutter** [comment]
> Please reopen this if you have crash logs to share.

I tried to get the log with setting > advanced> dump crash log. But I can not find the output file. Is anything wrong with my operation?

**Comment by Saud-97** [comment]
This is already fixed in https://github.com/tachiyomiorg/tachiyomi-extensions/pull/11997

**Comment by kasperskier** [comment]
If you have any of the following installed, this is already fixed. Please update extensions.
- Manga Cross
- Gufengmh
- Imitui

**Comment by brithbutter** [comment]
> If you have any of the following installed, this is already fixed. Please update extensions.
> 
> * Manga Cross
> * Gufengmh
> * Imitui

All extensions are updated. And the bug I mentioned can still be reproduced.

**Comment by brithbutter** [comment]
> This is already fixed in [tachiyomiorg/tachiyomi-extensions#11997](https://github.com/tachiyomiorg/tachiyomi-extensions/pull/11997)

I noticed this post. But my bug is not fixed. I think it's about the general logic of the library index update procedure.

**Comment by brithbutter** [comment]
> > If you have any of the following installed, this is already fixed. Please update extensions.
> > 
> > * Manga Cross
> > * Gufengmh
> > * Imitui
> 
> All extensions are updated. And the bug I mentioned can still be reproduced.

Just received an update of the extension, for now, the bug can not be reproduced again.
Thank you for the help.
