### ISSUE TITLE
Some pages disappear

### ISSUE THREAD

**Issue by hyoretsu** [tachiyomiorg/tachiyomi#7943]
### Steps to reproduce

Read some webtoons, and a page will get cut out. It happened to me in The World After the Fall episode 36 (randomly though, with downloaded chapters)

### Expected behavior

Shouldn't cut pages.

### Actual behavior

Cut pages.

### Tachiyomi version

r4884

### Android version

Android 10

### Device

Moto G7 Power

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Not 100% sure but should be fixed by #7947

**Comment by brazor421** [comment]
This bug still persists in r4904. Bug can happen with any webtoon on any source.

**Comment by ihocan** [comment]
Hi bug is really painfully on reading webtoon it's exist on r4904 also.
It's can be reproduce like below step,

1. Open any webtoon from any source, currently I'm reading "Regressor Instruction Manual" from "IsekaiScan.com"
2. when i open "chapter 23" it's firstly loaded as 3 page a lot of missing page because it's must be 8 page.
3. closed the page directly opened from library, it's loaded 5 page it's again have mising page.
4. i closed and opened again it's loaded all page.
I'm facing this issue on all webtoon, it's not doing this each chapter.

**Comment by VirusEcks** [comment]
i noticed that bug with the split tall images set to on in the reader settings webtoon section
but it was solved after turning it off

**Comment by brazor421** [comment]
> i noticed that bug with the split tall images set to on in the reader settings webtoon section but it was solved after turning it off
Yep, turning this function off solved this problem. Thx for the tip. At least for now I haven't had that bug.

**Comment by kuroko14** [comment]
> i noticed that bug with the split tall images set to on in the reader settings webtoon section but it was solved after turning it off

You are a life saver

**Comment by mrehanabbasi** [comment]
> i noticed that bug with the split tall images set to on in the reader settings webtoon section
> but it was solved after turning it off

You are a life saver. Been reading this way for weeks but now I can finally relax.

**Comment by stevenyomi** [comment]
Duplicate of #8433
